### ISSUE TITLE
Explore "featured content" on AsciiDoc start page

### ISSUE THREAD

**Issue by ahus1** [EclipseFdn/asciidoc-wg.eclipse.org#37]
In issue #29 and PR #34 / 3c3750013e0ce02e13a8082e1b27c17b5486554f we've replace the "featured content" (at that time mentioning the "Eclipse Foundation Events") with content hosted in the AsciiDoc WG Git repo describing the "purpose" of the AsciiDoc working group.

As pointed out by @chrisguindon, the Eclipse Marketing team maintains and updates the content delivered for the "featured content" widget on the site. 
@shanda-eclipse let us know that we can send content to her via email: news@eclipse.org

This is a follow-up issue to find out: 

* what are the trade-offs of using the "featured story" mechanism delivering dynamic content vs. static content on the working group's start page?
* who is responsible/the driver for the content of the "featured story" - the working group or the Eclipse Marketing team?
* what are recommendations/best practices of the Eclipse Marketing team to have on a working group's start page?

Possible outcomes of this issue: 
* stay with having the content in the git repository OR using the featured story mechanism with content maintained by the Eclipse Marketing team
* stay with the "purpose" content OR come up with different content that fits better to the start page

**Comment by ahus1** [comment]
Hi @shanda-eclipse, as mentioned in the previous issue I don't fully understand the "featured story" workflow the intentions behind it. Could you please shed some light on it for me how it is supposed to work / the problems it solves / the goals it pursues? 

As described above, I'd like to find out if there is something we should change or if we should keep it the way it is now, 

Thanks!

**Comment by chrisguindon** [comment]
To clarify, I would expect the featured footer to exist on the site not the one at the top of the page.

I will let @shanda-eclipse explain how they use it but the short version is for promoting surveys, case studies, projects. events or any other marketing-related content.

We created this workflow to reduce the maintenance burden for the web dev team. Previously, adding a news item or featured story on the website required someone to 1) create an issue, 2) assign a developer, 3) implement the change, 4) code review, and finally 5) PR merged which in return deploys the site.

We created the newsroom to remove my team from this process. (We are still involved behind the scene by keeping the newsroom website up-to-date but we are no longer required to push time-sensitive content on the site).

The featured footer at the top of the page is optional but most WG websites will include the featured footer.

![Screenshot from 2021-04-06 16-20-23](https://user-images.githubusercontent.com/893942/113773500-1c8b2600-96f4-11eb-9a28-ab751266fa3d.png)

My recommendation for this site is not to replace the behavior but simply add your own section that can be repeated on all pages before the EF Featured footer.

**Comment by shanda-eclipse** [comment]
As @chrisguindon mentioned, the featured story section is used by the foundation marketing team to promote white papers, case studies, announcements/project updates, or give extra attention to a specific event or social channels. This feature is used across working group sites so that the foundation marketing team can easily push out updates on a regular basis. It also gives us the opportunity to have 2-3 messages in rotation, so that on each reload of the site the message in that section is different.

Some working groups have new content in this section weekly, whereas other working groups keep the same content for months at a time. It really depends how active the working group is and what objectives you are trying to achieve with the site. 

The foundation team has a few CTAs (call-to-action) we will add to the working group sites if there is nothing else to put in the section, such as:
- Check out our upcoming events
- Become a member
- EclipseCon call for proposals

But this is of course the working group's site, so if there is a message you would like or would like to remove you can always contact us through news@eclipse.org and we can work on updating that section together. 

Hope this helps clarify the functionality of the featured stories.

**Comment by ahus1** [comment]
Thanks for your input. I see that the AsciiDoc WG site already has the featured content in the footer on all pages including the start page, and we will keep it that way. Therefore, there is no further todo for us now, therefore I close this issue. 

The Eclipse Marketing Team will publish new content when they need to - and we're fine with that. 

Once the AsciiDoc WG wants to add content to the rotation on its own site or on other sites, it will contact news@eclipse.org

Please comment if I misunderstood anything and I'll re-open this issue.
